// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using movie_restful_api_csharp.Data;

#nullable disable

namespace movie_restful_api_csharp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230424152806_migration")]
    partial class migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("movie_system_csharp.Models.GenreModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TmdbId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Explosions, Guns & Violence",
                            Title = "Action",
                            TmdbId = 28
                        },
                        new
                        {
                            Id = 2,
                            Description = "Explore new things",
                            Title = "Adventure",
                            TmdbId = 12
                        },
                        new
                        {
                            Id = 3,
                            Description = "Let ur drawings come to life",
                            Title = "Animation",
                            TmdbId = 16
                        },
                        new
                        {
                            Id = 4,
                            Description = "Jokes & laughter",
                            Title = "Comedy",
                            TmdbId = 35
                        },
                        new
                        {
                            Id = 5,
                            Description = "Murder mystery's & underground societys",
                            Title = "Crime",
                            TmdbId = 80
                        },
                        new
                        {
                            Id = 6,
                            Description = "Learn about reality & its wonders",
                            Title = "Documentary",
                            TmdbId = 99
                        },
                        new
                        {
                            Id = 7,
                            Description = "conflict, emotional, social or otherwise",
                            Title = "Drama",
                            TmdbId = 18
                        },
                        new
                        {
                            Id = 8,
                            Description = "fun for the whole family",
                            Title = "Family",
                            TmdbId = 10751
                        },
                        new
                        {
                            Id = 9,
                            Description = "Dragons, Elfs & Magic",
                            Title = "Fantasy",
                            TmdbId = 14
                        },
                        new
                        {
                            Id = 10,
                            Description = "A look back at our history",
                            Title = "History",
                            TmdbId = 36
                        },
                        new
                        {
                            Id = 11,
                            Description = "Terror, Schock & everyhing that makes u scream",
                            Title = "Horror",
                            TmdbId = 27
                        },
                        new
                        {
                            Id = 12,
                            Description = "Musicals & Melody",
                            Title = "Music",
                            TmdbId = 10402
                        },
                        new
                        {
                            Id = 13,
                            Description = "What where and how? lets find out",
                            Title = "Mystery",
                            TmdbId = 9648
                        },
                        new
                        {
                            Id = 14,
                            Description = "a love afair",
                            Title = "Romance",
                            TmdbId = 10749
                        },
                        new
                        {
                            Id = 15,
                            Description = "futuristic lands & techolegy",
                            Title = "Science Fiction",
                            TmdbId = 878
                        },
                        new
                        {
                            Id = 16,
                            Description = "Ur favorit Tv show made a movie",
                            Title = "TV Movie",
                            TmdbId = 10770
                        },
                        new
                        {
                            Id = 17,
                            Description = "Suspense, excitement, surprise, anticipation and anxiety",
                            Title = "Thriller",
                            TmdbId = 53
                        },
                        new
                        {
                            Id = 18,
                            Description = "Warfare & battles",
                            Title = "War",
                            TmdbId = 10752
                        },
                        new
                        {
                            Id = 19,
                            Description = "Cowboys, Cowgirls & Bandits",
                            Title = "Western",
                            TmdbId = 37
                        });
                });

            modelBuilder.Entity("movie_system_csharp.Models.LikedGenreModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("GenreId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.HasIndex("UserId");

                    b.ToTable("LikedGenres");
                });

            modelBuilder.Entity("movie_system_csharp.Models.MovieGenreModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("GenreId")
                        .HasColumnType("int");

                    b.Property<int?>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.HasIndex("MovieId");

                    b.ToTable("MovieGenres");
                });

            modelBuilder.Entity("movie_system_csharp.Models.MovieModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Link")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Moveis");
                });

            modelBuilder.Entity("movie_system_csharp.Models.MovieRatingModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("GenreModelId")
                        .HasColumnType("int");

                    b.Property<int?>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GenreModelId");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("MovieRatings");
                });

            modelBuilder.Entity("movie_system_csharp.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("movie_system_csharp.Models.LikedGenreModel", b =>
                {
                    b.HasOne("movie_system_csharp.Models.GenreModel", "Genres")
                        .WithMany("LikedGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("movie_system_csharp.Models.UserModel", "Users")
                        .WithMany("LikedGenres")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Genres");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("movie_system_csharp.Models.MovieGenreModel", b =>
                {
                    b.HasOne("movie_system_csharp.Models.GenreModel", "Genres")
                        .WithMany("MovieGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("movie_system_csharp.Models.MovieModel", "Movies")
                        .WithMany("MovieGenres")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Genres");

                    b.Navigation("Movies");
                });

            modelBuilder.Entity("movie_system_csharp.Models.MovieModel", b =>
                {
                    b.HasOne("movie_system_csharp.Models.UserModel", "Users")
                        .WithMany("Movies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Users");
                });

            modelBuilder.Entity("movie_system_csharp.Models.MovieRatingModel", b =>
                {
                    b.HasOne("movie_system_csharp.Models.GenreModel", null)
                        .WithMany("MovieRatings")
                        .HasForeignKey("GenreModelId");

                    b.HasOne("movie_system_csharp.Models.MovieModel", "Movies")
                        .WithMany("MovieRatings")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("movie_system_csharp.Models.UserModel", "Users")
                        .WithMany("MovieRatings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Movies");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("movie_system_csharp.Models.GenreModel", b =>
                {
                    b.Navigation("LikedGenres");

                    b.Navigation("MovieGenres");

                    b.Navigation("MovieRatings");
                });

            modelBuilder.Entity("movie_system_csharp.Models.MovieModel", b =>
                {
                    b.Navigation("MovieGenres");

                    b.Navigation("MovieRatings");
                });

            modelBuilder.Entity("movie_system_csharp.Models.UserModel", b =>
                {
                    b.Navigation("LikedGenres");

                    b.Navigation("MovieRatings");

                    b.Navigation("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
